### ISSUE TITLE
Create Firebase Project

### ISSUE THREAD

**Issue by ryan-christopher** [ryan-christopher/CS673-TerrierMap#8]
Here we begin to create the Firebase project for our application

- [x] Create an initial firebase project
- [x] Share project with everyone
- [ ] Connecting Next app

**Comment by JasNotTheGenre** [comment]
Here's the link to the .json file I made
https://drive.google.com/file/d/13s9KtAsvhyKuRCoAmLxAOugVS_ieGmhc/view?usp=drive_link

Here's a link to the google sheet with the database input thingys
https://docs.google.com/spreadsheets/d/1yCVMUR5zN0ubUi9LNmbHjTnncO9B0mc0puORXSILEe0/edit?gid=0#gid=0

**Comment by JasNotTheGenre** [comment]
Here's the Firebase project. I'll add everyone's bu emails shortly unless someone replies with a different email.

https://console.firebase.google.com/u/0/project/terriermap/database/terriermap-default-rtdb/data

**Comment by JasNotTheGenre** [comment]
@mgared Were you ever able to make sure the firebase was set up correctly?
